# Data check

In [20]:
from datasets import load_dataset
from transformers import AutoTokenizer
import numpy as np

In [3]:
dataset = load_dataset("openai/gsm8k", "main")

In [6]:
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-1B")

In [28]:
# Train set
q_tokens = tokenizer.batch_encode_plus(dataset["train"]["question"])
a_tokens = tokenizer.batch_encode_plus(dataset["train"]["answer"])

n_tokens = {
    "n_q_tokens": [],
    "n_a_tokens": [],
}
for q, a in zip(q_tokens["input_ids"], a_tokens["input_ids"]):
    n_tokens["n_q_tokens"].append(len(q))
    n_tokens["n_a_tokens"].append(len(a))

n_q_tokens = np.array(n_tokens["n_q_tokens"])
n_q_tokens.sort()
n_a_tokens = np.array(n_tokens["n_a_tokens"])
n_a_tokens.sort()

n_q_tokens, n_a_tokens

(array([ 12,  18,  19, ..., 183, 184, 210]),
 array([ 23,  23,  23, ..., 319, 333, 362]))

In [27]:
# Test set
q_tokens = tokenizer.batch_encode_plus(dataset["test"]["question"])
a_tokens = tokenizer.batch_encode_plus(dataset["test"]["answer"])

n_tokens = {
    "n_q_tokens": [],
    "n_a_tokens": [],
}
for q, a in zip(q_tokens["input_ids"], a_tokens["input_ids"]):
    n_tokens["n_q_tokens"].append(len(q))
    n_tokens["n_a_tokens"].append(len(a))

n_q_tokens = np.array(n_tokens["n_q_tokens"])
n_q_tokens.sort()
n_a_tokens = np.array(n_tokens["n_a_tokens"])
n_a_tokens.sort()

n_q_tokens, n_a_tokens

(array([ 23,  24,  24, ..., 157, 163, 186]),
 array([ 23,  30,  32, ..., 277, 290, 311]))